const productsToAdd = [
  {
    name: "Buick Media Center",
    description: "amet nulla. Donec non justo. Proin non massa non ante",
    image: "https://i.imgur.com/SBm32LX.png",
    stock: 11,
    price: 1299,
    reviewstars: 4,
    category: "Living Room",
  },
  {
    name: "Konway Classical 2 Seater Sofa",
    description:
      "sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.",
    image: "https://i.imgur.com/ruj2sTH.jpg",
    stock: 52,
    price: 799,
    reviewstars: 3,
    category: "Living Room",
  },
  {
    name: "Celene Coffee Table",
    description: "amet nulla. Donec non justo. Proin non massa non ante",
    image: "https://i.imgur.com/zZgRePf.jpg",
    stock: 23,
    price: 518,
    reviewstars: 5,
    category: "Living Room",
  },
  {
    name: "Billy Dark Wood TV Stand",
    description:
      "urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.",
    image: "https://i.imgur.com/H4qESnO.png",
    stock: 5,
    price: 303,
    reviewstars: 1,
    category: "Living Room",
  },
  {
    name: "Twitty Bookcase",
    description:
      "quam. Pellentesque habitant morbi tristique senectus et netus et malesuada",
    image: "https://i.imgur.com/cTh8gb3.png",
    stock: 6,
    price: 1477,
    reviewstars: 5,
    category: "Living Room",
  },
  {
    name: "Schaerfler Living Room Set",
    description:
      "quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus",
    image: "https://i.imgur.com/NwoxGTp.png",
    stock: 0,
    price: 5433,
    reviewstars: 5,
    category: "Living Room",
  },
  {
    name: "Twain Traditional 3 Seater Sofa",
    description: "ante dictum mi, ac mattis velit justo nec ante. Maecenas",
    image: "https://i.imgur.com/OTQJhgH.jpg",
    stock: 11,
    price: 616,
    reviewstars: 5,
    category: "Living Room",
  },
  {
    name: "Smolly Classic Love Sofa",
    description:
      "libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet",
    image: "https://i.imgur.com/s9OvTlm.jpg",
    stock: 20,
    price: 349,
    reviewstars: 3,
    category: "Living Room",
  },
  {
    name: "Gravida Swing Accent Chair",
    description: "sit amet, risus. Donec nibh enim, gravida sit amet, dapibus",
    image: "https://i.imgur.com/dpvHqxG.jpg",
    stock: 10,
    price: 233,
    reviewstars: 4,
    category: "Living Room",
  },
  {
    name: "Metus Bar & Table",
    description: "metus. In nec orci. Donec nibh. Quisque nonummy ipsum non",
    image: "https://i.imgur.com/UXpa8U4.jpg",
    stock: 28,
    price: 518,
    reviewstars: 4,
    category: "Living Room",
  },
  {
    name: "Bugey Sofa",
    description:
      "ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,",
    image: "https://i.imgur.com/0uw14OP.jpg",
    stock: 12,
    price: 160,
    reviewstars: 2,
    category: "Living Room",
  },
  {
    name: "Saucey End Table",
    description:
      "malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.",
    image: "https://i.imgur.com/weXlmQ7.jpg",
    stock: 18,
    price: 82,
    reviewstars: 5,
    category: "Living Room",
  },
  {
    name: "Convallis Dining Set",
    description:
      "amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis",
    image: "https://i.imgur.com/k9SzT8w.png",
    stock: 25,
    price: 1410,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Ultrices Round Dining Table",
    description: "blandit at, nisi. Cum sociis natoque penatibus et magnis dis",
    image: "https://i.imgur.com/9rajxdc.png",
    stock: 28,
    price: 455,
    reviewstars: 4,
    category: "Dining Room",
  },
  {
    name: "Sid Modern Dining Chair",
    description: "a, auctor non, feugiat nec, diam. Duis mi enim, condimentum",
    image: "https://i.imgur.com/l6vSIG8.jpg",
    stock: 30,
    price: 182,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Diam Dining Set",
    description:
      "penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean",
    image: "https://i.imgur.com/2gQatt8.jpg",
    stock: 9,
    price: 1119,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Retro Dining Room Chair",
    description:
      "Aenean gravida nunc sed pede. Cum sociis natoque penatibus et",
    image: "https://i.imgur.com/wlRFyd4.jpg",
    stock: 25,
    price: 49,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Ligula Experience Dining Chair",
    description:
      "magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu",
    image: "https://i.imgur.com/Uh21Q3g.jpg",
    stock: 26,
    price: 325,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Tincidunt Dining Table",
    description: "ornare tortor at risus. Nunc ac sem ut dolor dapibus",
    image: "https://i.imgur.com/ErndGCL.png",
    stock: 27,
    price: 799,
    reviewstars: 5,
    category: "Dining Room",
  },
  {
    name: "Brent Dining Room Set",
    description: "pede et risus. Quisque libero lacus, varius et, euismod et,",
    image: "https://i.imgur.com/8GBDj29.jpg",
    stock: 14,
    price: 696,
    reviewstars: 5,
    category: "Dining Room Set",
  },
  {
    name: "Dodgey Dining Chair",
    description:
      "nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod",
    image: "https://i.imgur.com/tTZ7S8q.jpg",
    stock: 15,
    price: 37,
    reviewstars: 4,
    category: "Dining Room",
  },
  {
    name: "Neo Mesh Dining Chair",
    description:
      "massa non ante bibendum ullamcorper. Duis cursus, diam at pretium",
    image: "https://i.imgur.com/FTYGDjQ.png",
    stock: 24,
    price: 40,
    reviewstars: 4,
    category: "Dining Room",
  },
];

const ordersToCreate = [
  {
    email: "ipsum.porta.elit@protonmail.ca",
    street: "Ap #677-2045 Dictum. Ave",
    city: "Murcia",
    zipcode: "542538",
    country: "Vietnam",
    phone: "(378) 713-2327",
    price: 113,
    userId: 10,
  },
  {
    email: "mauris.vel.turpis@protonmail.org",
    street: "P.O. Box 869, 5322 Duis Avenue",
    city: "Sungei Kadut",
    zipcode: "81175",
    country: "South Korea",
    phone: "1-886-415-3523",
    price: 198,
    userId: 3,
  },
  {
    email: "vel.arcu.eu@hotmail.edu",
    street: "548 Iaculis Rd.",
    city: "Kapolei",
    zipcode: "967988",
    country: "Sweden",
    phone: "(259) 814-1832",
    price: 39,
    userId: 14,
  },
  {
    email: "eleifend.non.dapibus@aol.com",
    street: "8505 Enim Rd.",
    city: "Nizip",
    zipcode: "8572",
    country: "China",
    phone: "1-343-573-5247",
    price: 412,
    userId: 4,
  },
  {
    email: "sed@protonmail.couk",
    street: "6871 Pede. Rd.",
    city: "Haren",
    zipcode: "920136",
    country: "Peru",
    phone: "(844) 855-3575",
    price: 10,
    userId: 4,
  },
  {
    email: "malesuada@yahoo.couk",
    street: "9700 Nunc St.",
    city: "Los Vilos",
    zipcode: "292744",
    country: "Austria",
    phone: "(330) 461-6184",
    price: 447,
    userId: 6,
  },
  {
    email: "dolor.donec.fringilla@yahoo.org",
    street: "284 Vel, Street",
    city: "Aparecida de Goiânia",
    zipcode: "24017",
    country: "Spain",
    phone: "(945) 751-2560",
    price: 262,
    userId: 12,
  },
  {
    email: "eget.ipsum@aol.com",
    street: "582 Lacus Rd.",
    city: "Chancay",
    zipcode: "31862",
    country: "Belgium",
    phone: "(977) 545-5035",
    price: 19,
    userId: 6,
  },
  {
    email: "ornare.placerat@yahoo.couk",
    street: "P.O. Box 766, 8262 Eu Av.",
    city: "Port Nolloth",
    zipcode: "12266",
    country: "Vietnam",
    phone: "(864) 486-1513",
    price: 92,
    userId: 4,
  },
  {
    email: "lorem.ipsum@google.com",
    street: "6351 Luctus St.",
    city: "Guizhou",
    zipcode: "88262",
    country: "Spain",
    phone: "(368) 112-2658",
    price: 496,
    userId: 3,
  },
  {
    email: "pede.malesuada.vel@outlook.edu",
    street: "551-2290 Varius. Avenue",
    city: "Seloignes",
    zipcode: "225398",
    country: "United States",
    phone: "(355) 719-7074",
    price: 254,
    userId: 10,
  },
  {
    email: "at.pede@hotmail.org",
    street: "611-9564 Vestibulum Avenue",
    city: "Sokoto",
    zipcode: "549374",
    country: "Sweden",
    phone: "1-678-478-2363",
    price: 250,
    userId: 7,
  },
  {
    email: "nam@yahoo.couk",
    street: "336-5191 Ante St.",
    city: "General Santos",
    zipcode: "887264",
    country: "Belgium",
    phone: "(746) 365-6148",
    price: 455,
    userId: 15,
  },
  {
    email: "lobortis.mauris.suspendisse@aol.net",
    street: "P.O. Box 881, 7575 Diam St.",
    city: "Dubno",
    zipcode: "15521",
    country: "Canada",
    phone: "(777) 423-1597",
    price: 8,
    userId: 0,
  },
  {
    email: "rhoncus.id.mollis@outlook.edu",
    street: "825-5678 Volutpat. Street",
    city: "Emalahleni",
    zipcode: "45135",
    country: "Nigeria",
    phone: "1-280-992-5537",
    price: 462,
    userId: 10,
  },
  {
    email: "consectetuer.adipiscing.elit@aol.edu",
    street: "950-9572 Sit Street",
    city: "Kirkintilloch",
    zipcode: "02541",
    country: "Brazil",
    phone: "1-964-345-1420",
    price: 424,
    userId: 2,
  },
  {
    email: "vulputate@protonmail.edu",
    street: "Ap #701-679 Eget, Rd.",
    city: "Recife",
    zipcode: "22618",
    country: "Canada",
    phone: "(861) 484-3844",
    price: 14,
    userId: 7,
  },
  {
    email: "egestas.hendrerit@yahoo.couk",
    street: "233-9628 Ipsum. Street",
    city: "Monfumo",
    zipcode: "31183",
    country: "China",
    phone: "1-442-311-6831",
    price: 408,
    userId: 10,
  },
  {
    email: "tincidunt@icloud.ca",
    street: "681-3680 Mauris Av.",
    city: "Liaoning",
    zipcode: "6155-9518",
    country: "Russian Federation",
    phone: "1-354-477-4566",
    price: 491,
    userId: 19,
  },
  {
    email: "non.egestas@hotmail.edu",
    street: "835-8352 Odio. Av.",
    city: "Newton",
    zipcode: "5424 YG",
    country: "Vietnam",
    phone: "1-889-569-3426",
    price: 83,
    userId: 0,
  },
  {
    email: "magna.nam@yahoo.couk",
    street: "Ap #136-206 Donec Road",
    city: "Iloilo City",
    zipcode: "5347",
    country: "Peru",
    phone: "(775) 308-2306",
    price: 218,
    userId: 5,
  },
  {
    email: "diam.luctus@yahoo.com",
    street: "163-8937 Lacus. Av.",
    city: "Belfast",
    zipcode: "447595",
    country: "Canada",
    phone: "1-408-781-1284",
    price: 69,
    userId: 2,
  },
  {
    email: "sed.pede@icloud.org",
    street: "Ap #393-2879 Non, Street",
    city: "Ipiales",
    zipcode: "36302",
    country: "Netherlands",
    phone: "1-790-617-3665",
    price: 266,
    userId: 20,
  },
  {
    email: "a.scelerisque@outlook.couk",
    street: "P.O. Box 742, 3180 Diam St.",
    city: "Calapan",
    zipcode: "7764",
    country: "Germany",
    phone: "(223) 242-2793",
    price: 226,
    userId: 12,
  },
  {
    email: "metus@google.ca",
    street: "752-1109 Lacus. Road",
    city: "Lleida",
    zipcode: "735650",
    country: "Belgium",
    phone: "(782) 303-3521",
    price: 27,
    userId: 3,
  },
  {
    email: "luctus@hotmail.edu",
    street: "557-9080 Morbi Av.",
    city: "Tarnów",
    zipcode: "024293",
    country: "Vietnam",
    phone: "1-425-705-4448",
    price: 181,
    userId: 17,
  },
  {
    email: "interdum.ligula@hotmail.ca",
    street: "977-6275 Lacus Rd.",
    city: "Bo‘lhe",
    zipcode: "4557 XL",
    country: "Sweden",
    phone: "(589) 481-7642",
    price: 480,
    userId: 20,
  },
  {
    email: "suspendisse.dui.fusce@outlook.net",
    street: "Ap #820-6049 Semper Road",
    city: "Jhang",
    zipcode: "82803",
    country: "Netherlands",
    phone: "(552) 631-1771",
    price: 271,
    userId: 20,
  },
  {
    email: "donec.tincidunt.donec@icloud.org",
    street: "Ap #226-9492 Nunc Rd.",
    city: "Skövde",
    zipcode: "97431",
    country: "Italy",
    phone: "1-876-692-3470",
    price: 278,
    userId: 18,
  },
  {
    email: "aliquam.vulputate@aol.edu",
    street: "356-6178 Ac Rd.",
    city: "Darbhanga",
    zipcode: "157210",
    country: "Costa Rica",
    phone: "1-576-774-5204",
    price: 161,
    userId: 19,
  },
  {
    email: "morbi.tristique.senectus@google.couk",
    street: "467-6965 Interdum Avenue",
    city: "Rodgau",
    zipcode: "78804-67150",
    country: "Australia",
    phone: "(693) 481-8573",
    price: 131,
    userId: 20,
  },
];

// // const cartToCreate = [
// //   {

// //     productId: product1.id,
// //     ordersId: order1.id,
// //     price: 30,
// //     quantity: 5,
// //   },

// // ];

const usersToCreate = [
  {
    username: "Ramses",
    password: "ramses1!",
    email: "ramses@gmail.com",
    firstname: "Ramses",
    lastname: "Angles",
    orderStatus: "admin",
  },
  {
    username: "HPS76LC",
    email: "morbi.tristique.senectus@google.couk",
    password: "JIS22JDU0VX",
    firstname: "Shea",
    lastname: "Spears",
    orderStatus: "user",
  },
  {
    username: "IUB22IP",
    email: "aliquam.vulputate@aol.edu",
    password: "MEB53FOU6PR",
    firstname: "Clio",
    lastname: "Cox",
    orderStatus: "user",
  },
  {
    username: "TOF38MY",
    email: "donec@icloud.org",
    password: "IFQ77QTI0BR",
    firstname: "Conan",
    lastname: "Burris",
    orderStatus: "admin",
  },
  {
    username: "EPJ35JN",
    email: "arcu@yahoo.net",
    password: "XYG71QYZ8IH",
    firstname: "Vernon",
    lastname: "Kidd",
    orderStatus: "admin",
  },
  {
    username: "KNL86FH",
    email: "pellentesque@aol.org",
    password: "CXS18BTJ8BF",
    firstname: "Kato",
    lastname: "Black",
    orderStatus: "admin",
  },
  {
    username: "XBY77WQ",
    email: "enim.sit@icloud.com",
    password: "JUG94FVJ9DV",
    firstname: "Cassandra",
    lastname: "Keith",
    orderStatus: "user",
  },
  {
    username: "EXU91HW",
    email: "purus@outlook.net",
    password: "DOX63WRV4OY",
    firstname: "Nero",
    lastname: "Morales",
    orderStatus: "admin",
  },
  {
    username: "XEZ38EF",
    email: "luctus.et@hotmail.ca",
    password: "SKB63JZI5BH",
    firstname: "Maryam",
    lastname: "Jimenez",
    orderStatus: "admin",
  },
  {
    username: "TBC84DN",
    email: "gravida.mauris@hotmail.net",
    password: "HOR46LHW2PO",
    firstname: "Leigh",
    lastname: "Miranda",
    orderStatus: "user",
  },
  {
    username: "ULI30WX",
    email: "elit.nulla@aol.couk",
    password: "VOT64GES0DU",
    firstname: "Amal",
    lastname: "Patrick",
    orderStatus: "user",
  },
  {
    username: "HVQ84QT",
    email: "et@aol.com",
    password: "GBL81OWZ1FT",
    firstname: "Cyrus",
    lastname: "Whitehead",
    orderStatus: "admin",
  },
  {
    username: "NUF77QX",
    email: "convallis@google.couk",
    password: "BQK38YYH0BB",
    firstname: "Bethany",
    lastname: "Solomon",
    orderStatus: "admin",
  },
  {
    username: "JVY17GM",
    email: "mus.donec.dignissim@yahoo.org",
    password: "FSK16GUY8XX",
    firstname: "Rhona",
    lastname: "Estrada",
    orderStatus: "admin",
  },
  {
    username: "FQB86XC",
    email: "ultrices.mauris.ipsum@protonmail.couk",
    password: "LGN55OGN9NN",
    firstname: "Erin",
    lastname: "Duffy",
    orderStatus: "admin",
  },
  {
    username: "QTX82PK",
    email: "sed.neque@yahoo.edu",
    password: "KDG63BEB6ZB",
    firstname: "Clinton",
    lastname: "Dillard",
    orderStatus: "user",
  },
  {
    username: "SJO44OE",
    email: "diam@aol.edu",
    password: "LLP38NCH6BL",
    firstname: "Judah",
    lastname: "Schroeder",
    orderStatus: "admin",
  },
  {
    username: "QKP02TJ",
    email: "ornare.fusce@protonmail.ca",
    password: "FHG03IBK3BK",
    firstname: "Solomon",
    lastname: "Bradley",
    orderStatus: "user",
  },
  {
    username: "CEG78DE",
    email: "sit.amet@protonmail.couk",
    password: "PJC66OIH8FI",
    firstname: "Justin",
    lastname: "Daniel",
    orderStatus: "user",
  },
  {
    username: "QQS69SY",
    email: "non@google.org",
    password: "IWF41GQX7BC",
    firstname: "Chanda",
    lastname: "Oneil",
    orderStatus: "admin",
  },
];

module.exports = {
  productsToAdd,
  ordersToCreate,
  usersToCreate,
};
